'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, Headphones, Menu, Play, SlidersHorizontal, X } from 'lucide-react'
import { offer } from '@/lib/offer-config'

const modules = [
  ['01', 'Foundations', 'Build the right listening framework, session structure, and vocal-first mindset before touching a plugin.'],
  ['02', 'Vocal Processing', 'Shape clarity, warmth, dynamics, and presence for a confident Naat vocal.'],
  ['03', 'Pitch & Timing', 'Make subtle, musical corrections that support the performance without making it feel artificial.'],
  ['04', 'Sound Design', 'Create the spacious, intimate atmosphere that gives a Naat production its emotional identity.'],
  ['05', 'Mixing', 'Bring vocals, instruments, ambience, and effects together in a balanced Studio One workflow.'],
  ['06', 'Mastering', 'Prepare a clean, controlled master for streaming, video, and real-world listening systems.'],
  ['07', 'Final Project', 'Apply the complete workflow to a finished Naat production from first listen to final export.'],
]
const faqs = [
  ['Is this course beginner-friendly?', 'Yes. The path starts with foundations and builds toward a complete final project, so you can follow the workflow even if you are new to professional Naat production.'],
  ['Do I need Studio One?', 'The practical workflow is taught in Studio One. You will need access to a PC or laptop with Studio One to follow along and complete the project.'],
  ['What is included in the ₹4,999 masterclass?', 'You get the complete 7-module curriculum, 20 classes, 25+ hours of lessons, the final Naat production project, mixing and mastering workflow, and lifetime access.'],
  ['What are the optional digital products?', 'The Vocal Preset Pack and MIDI Chord Bundle are separate paid tools. They are optional additions to the masterclass and are not included in the course price.'],
  ['Can I watch on mobile?', 'You can access the lessons on mobile, tablet, or desktop. A PC or laptop is recommended for the hands-on Studio One work.'],
  ['What is the refund policy?', 'Please review the refund terms shown at checkout before purchasing. Software, equipment, and third-party plugin costs are not part of the masterclass.'],
]

function Button({ children, href }: { children: React.ReactNode; href?: string }) { return <a className="button button-primary" href={href || '#offer'}>{children}<ArrowRight size={16} /></a> }
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="eyebrow"><span />{children}</p> }
function Waveform({ processed = false }: { processed?: boolean }) { return <div className={`waveform ${processed ? 'processed' : ''}`} aria-hidden="true">{Array.from({ length: 68 }, (_, i) => <i key={i} style={{ height: `${processed ? 25 + ((i * 17) % 65) : 7 + ((i * 11) % 25)}%` }} />)}</div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [playing, setPlaying] = useState(false)
  return <main>
    <nav className="nav"><a className="brand" href="#top" aria-label="SMN Studio home"><span className="brand-mark">A<span>V</span></span><span>SMN <b>STUDIO</b></span></a><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#workflow" onClick={() => setMenuOpen(false)}>The workflow</a><a href="#curriculum" onClick={() => setMenuOpen(false)}>Curriculum</a><a href="#about" onClick={() => setMenuOpen(false)}>Instructor</a><a href="#offer" onClick={() => setMenuOpen(false)}>Offer</a></div><a className="nav-cta" href="#offer">Explore masterclass <ArrowRight size={15} /></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button></nav>
    <section className="hero" id="top"><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="hero-content"><p className="kicker">SMN STUDIO · SOUND DESIGN EDUCATION</p><h1>Make your Naat<br /><em>sound like it feels.</em></h1><p className="hero-copy">A complete, practical workflow for turning a raw Naat vocal into a clean, emotional, professional production — taught by Arif Sagar.</p><div className="hero-actions"><Button>See the masterclass</Button><a className="text-link" href="#listen"><Play size={15} fill="currentColor" /> Hear the transformation</a></div><div className="hero-proof"><span><strong>25+</strong> hours</span><span><strong>20</strong> classes</span><span><strong>7</strong> modules</span></div></div><div className="hero-art"><div className="art-grid" /><div className="console"><div className="console-top"><span>SMN / SESSION 07</span><span>NAAT_VOCAL_MASTER</span><span>◉ 72 BPM</span></div><div className="console-screen"><div className="screen-title">Vocal Atmosphere <small>final mix</small></div><Waveform processed /><div className="console-faders"><i /><i /><i /><i /><i /></div></div><div className="console-bottom"><span>INPUT</span><span>EQ</span><span>COMPRESSOR</span><span>REVERB</span><span>OUTPUT</span></div></div><div className="hero-note"><Headphones size={16} /> Listen with headphones for the detail</div></div></section>
    <section className="listen section" id="listen"><div className="section-intro"><SectionLabel>THE TRANSFORMATION</SectionLabel><h2>Same voice.<br /><em>Different feeling.</em></h2><p>Before and after — an illustrative browser demo of the processing decisions you will learn inside the masterclass. The real workflow is yours to practice, repeat, and make your own.</p></div><div className="audio-card"><div className="audio-head"><span>ILLUSTRATIVE DEMO</span><span>RAW → PROCESSED</span></div><div className="audio-row"><button className="play-button" onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pause demo' : 'Play demo'}>{playing ? <span className="pause-icon" /> : <Play fill="currentColor" size={22} />}</button><div className="audio-tracks"><div className="track"><span>RAW VOCAL</span><Waveform /></div><div className="track"><span>PROCESSED VOCAL</span><Waveform processed /></div></div><span className="duration">0:28</span></div><div className="audio-foot"><span>{playing ? 'DEMO PLAYING' : 'PRESS PLAY TO PREVIEW'}</span><span>Generated demo — not a client recording</span></div></div></section>
    <section className="dark-band problem"><div className="split section"><div><SectionLabel>THE GAP</SectionLabel><h2>Good vocals deserve<br /><em>good decisions.</em></h2></div><div className="problem-copy"><p>Most Naat productions do not need more plugins. They need a clearer ear, a repeatable process, and the confidence to know what to do next.</p><p>When you understand the relationship between vocal, space, dynamics, and emotion, every session gets easier — and every performance gets more room to breathe.</p></div></div></section>
    <section className="section" id="workflow"><SectionLabel>THE WORKFLOW</SectionLabel><div className="section-heading"><h2>From first listen<br /><em>to final master.</em></h2><p>Six connected decisions. One calm, musical process you can use on every project.</p></div><div className="workflow-grid">{[['01','Listen','Hear what is really there before reaching for a plugin.'],['02','Clean','Remove distractions and create a stable foundation.'],['03','Shape','Give the vocal clarity, warmth, and controlled movement.'],['04','Place','Build depth and atmosphere around the performance.'],['05','Balance','Make every element support the message.'],['06','Finish','Export a master that translates beyond your room.']].map(([n,t,d]) => <div className="workflow-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowRight size={18} /></div>)}</div></section>
    <section className="section curriculum" id="curriculum"><div className="section-heading"><div><SectionLabel>WHAT YOU LEARN</SectionLabel><h2>A complete path,<br /><em>not scattered tips.</em></h2></div><p>Build skill through a structured sequence that moves from fundamentals to a finished Naat production.</p></div><div className="module-list">{modules.map(([n,t,d]) => <details key={n} open={n === '01'}><summary><span>{n}</span><b>{t}</b><i>{d}</i><ChevronDown size={18} /></summary></details>)}</div></section>
    <section className="about section" id="about"><div className="instructor-portrait"><img src="/images/arif-sagar-portrait.jpg" alt="Arif Sagar, Islamic Nasheed Artist and Sound Designer" /></div><div className="about-copy"><SectionLabel>YOUR INSTRUCTOR</SectionLabel><h2>Learn from the person<br /><em>behind the sound.</em></h2><p>Arif Sagar is an Islamic Nasheed Artist & Sound Designer and the founder of SMN Studio. He has been working in Naat and Nasheed production since 2012, teaching the listening decisions that make a mix feel intentional — not just the buttons that make it louder.</p><div className="credibility"><div><strong>Since 2012</strong><span>Naat & Nasheed production</span></div><div><strong>Arif Sagar</strong><span>Islamic Nasheed Artist & Sound Designer</span></div><div><strong>SMN Studio</strong><span>Founder-led practical workflow</span></div></div></div></section>
    <section className="reviews section" id="reviews"><div className="section-heading"><div><SectionLabel>STUDENT REVIEWS</SectionLabel><h2>Feedback from<br /><em>the SMN community.</em></h2></div><p>No named student review text was publicly verifiable in the official SMN pages supplied for this audit, so no testimonial or student identity is presented as proof.</p></div><div className="source-note"><span className="student-avatar" aria-hidden="true">SMN</span><div><h3>Authentic feedback source pending</h3><p>The official SMN Studio pages describe the studio, services, and course, but the accessible source content did not expose review names or review copy.</p><a className="text-link" href="https://smnstudio.in/home/" target="_blank" rel="noreferrer">Visit official SMN Studio <ArrowRight size={15} /></a></div></div></section>
    <section className="proof section" id="student-work"><div className="section-heading"><div><SectionLabel>FROM STUDENT TO CREATOR</SectionLabel><h2>Show the work<br /><em>when it is verifiable.</em></h2></div><p>No student YouTube URLs, thumbnails, or named student work items were exposed in the official SMN sources supplied for this audit. This section intentionally avoids invented links, images, names, and performance claims.</p></div><div className="source-note"><span className="student-avatar" aria-hidden="true">YT</span><div><h3>Student work source pending</h3><p>The official course page confirms the final project and student feedback class, but does not publish specific student YouTube work in the accessible page content.</p><a className="text-link" href="https://smnstudioacademy.gumroad.com/l/professional_plan" target="_blank" rel="noreferrer">View official course source <ArrowRight size={15} /></a></div></div></section>
    <section className="offer-section" id="offer"><div className="section offer"><div className="offer-copy"><SectionLabel>THE MASTERCLASS</SectionLabel><h2>Master the complete<br /><em>Naat sound design workflow.</em></h2><p>Everything you need to move from raw vocal to a confident, finished production — taught in a structured, practical path.</p><ul>{['7 modules · 20 classes · 25+ hours','Beginner → advanced progression','Studio One workflow','Mixing, mastering & final Naat project','Lifetime access'].map(x => <li key={x}><Check size={16} />{x}</li>)}</ul></div><div className="price-card"><span className="price-label">MASTERCLASS</span><div className="price">{offer.masterclass.price}</div><p>One-time payment · Lifetime access</p><Button>Start learning</Button><small>Secure checkout · Details shown before purchase</small></div></div></section>
    <section className="tools section"><div className="section-heading"><div><SectionLabel>OPTIONAL TOOLS</SectionLabel><h2>Extend your<br /><em>production workflow.</em></h2></div><p>Purpose-built digital tools to support your Naat production. These are optional paid products, separate from the masterclass.</p></div><div className="product-grid">{offer.products.map(product => <article className="product-card" key={product.id}><div className="product-image"><Image src={product.image} alt={`${product.name} product artwork`} fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div className="product-info"><span className="product-number">PRODUCT 0{product.id === 'vocal-preset-pack' ? '1' : '2'}</span><h3>{product.name}</h3><p className="subtitle">{product.subtitle}</p><div className="product-price"><s>{product.originalPrice}</s><strong>{product.price}</strong><span>Save {product.savings}</span></div><ul>{product.benefits.map(b => <li key={b}><Check size={15} />{b}</li>)}</ul><a className="button button-secondary" href={product.checkoutUrl || '#optional-tools'}>{product.id === 'vocal-preset-pack' ? 'Get the preset pack' : 'Get the MIDI bundle'} <ArrowRight size={16} /></a><small>Checkout link will be added when available.</small></div></article>)}</div></section>
    <section className="faq section" id="faq"><div className="faq-title"><SectionLabel>FAQ</SectionLabel><h2>Before you<br /><em>press play.</em></h2></div><div className="faq-list">{faqs.map(([q,a]) => <details key={q}><summary>{q}<ChevronDown size={18} /></summary><p>{a}</p></details>)}</div></section>
    <section className="final-cta"><SectionLabel>YOUR NEXT SESSION</SectionLabel><h2>Make space for<br /><em>the voice.</em></h2><p>Learn the process that lets a performance feel as powerful in the mix as it did in the room.</p><Button>Explore the masterclass</Button></section>
    <footer><a className="brand" href="#top"><span className="brand-mark">A<span>V</span></span><span>SMN <b>STUDIO</b></span></a><span>© 2026 SMN Studio · Islamic Naat Sound Design Masterclass</span><div><a href="#faq">FAQ</a><a href="#offer">Offer</a><a href="#top">Back to top ↑</a></div></footer>
  </main>
}
